# Generated by Django 5.0.4 on 2024-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
