# Generated by Django 5.0.4 on 2024-05-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
